"""empty message

Revision ID: 260f3ad99b3d
Revises: 
Create Date: 2018-09-19 14:07:50.253048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260f3ad99b3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('sso_id', sa.Integer(), nullable=True),
    sa.Column('account', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('depart_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_account_account'), 'account', ['account'], unique=True)
    op.create_table('bussiness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dropdowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('dtype', sa.Text(), nullable=False),
    sa.Column('stype', sa.Text(), nullable=False),
    sa.Column('ename', sa.Text(), nullable=False),
    sa.Column('cname', sa.Text(), nullable=False),
    sa.Column('cascade_type', sa.Text(), nullable=False),
    sa.Column('codition_type', sa.Text(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('rule', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('databases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('bussiness_id', sa.Integer(), nullable=False),
    sa.Column('dtype', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=False),
    sa.Column('port', sa.Text(), nullable=False),
    sa.Column('user', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['bussiness_id'], ['bussiness.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('bussiness_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('creater', sa.Text(), nullable=True),
    sa.Column('updater', sa.Text(), nullable=True),
    sa.Column('sort', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bussiness_id'], ['bussiness.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('coordinate_x', sa.Integer(), nullable=False),
    sa.Column('coordinate_y', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('charttype', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query_sql', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_model')
    op.drop_table('pages')
    op.drop_table('databases')
    op.drop_table('rule')
    op.drop_table('menu')
    op.drop_table('dropdowns')
    op.drop_table('bussiness')
    op.drop_index(op.f('ix_account_account'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
